<?php
/**
 * Created by PhpStorm.
 * User: Emma
 * Date: 23/10/2014
 * Time: 13:29
 */


// autoload.php @generated by Composer

require_once __DIR__ . '/composer' . '/autoload_real.php';

return ComposerAutoloaderInit2dad81e9d765ea40670aa4be29fbffbb::getLoader();
